export const PLAIN_LANGUAGE = {
  hierarchy: {
    Campaign: "Goal",
    "Ad Set": "Audience",
    Ad: "Ad",
  },
  fields: {
    objective: "What's your goal?",
    campaignName: "Give this goal a name",
    specialAdCategory: "Is this ad about housing, jobs, or credit?",
    dailyBudget: "Daily spending limit",
    lifetimeBudget: "Total budget for this goal",
    currency: "Currency",
    startDate: "When does this start?",
    endDate: "When does this end? (optional)",
    adSetName: "Name this audience",
    targeting: "Who should see this?",
    locations: "Where are they?",
    ageRange: "How old are they?",
    gender: "Gender",
    interests: "What are they into?",
    customAudience: "People who already know me",
    lookalikeAudience: "People similar to my customers",
    placements: "Where should the ad appear?",
    automaticPlacements: "Let Facebook decide (recommended)",
    manualPlacements: "I'll choose where it appears",
    optimizationGoal: "What do I want people to do?",
    bidStrategy: "How should we spend my budget?",
    bidAmount: "Max I'm willing to pay per result",
    billingEvent: "When do I get charged?",
    adName: "Name this ad",
    adFormat: "What type of ad?",
    primaryText: "Main message",
    headline: "Bold title",
    description: "Short extra detail",
    callToAction: "Button people click",
    destinationUrl: "Link where people land",
    adCreative: "Your image or video",
  },
  objectives: {
    CONVERSIONS: "Get people to buy",
    TRAFFIC: "Get people to visit my website",
    LEAD_GENERATION: "Collect contact info",
    REACH: "Show my ad to as many people as possible",
    BRAND_AWARENESS: "Make people know about me",
    AWARENESS: "Make people know about me",
    ENGAGEMENT: "Get people to like / comment / share",
    APP_PROMOTION: "Get app downloads",
    SALES: "Get people to buy",
  },
  bidStrategies: {
    LOWEST_COST: "Automatically get the best results",
    BID_CAP: "Limit my max cost per result",
    COST_CAP: "Keep my average cost below a limit",
  },
  formats: {
    SINGLE_IMAGE: "One image",
    VIDEO: "Video",
    CAROUSEL: "Multiple images (swipeable)",
    COLLECTION: "Product showcase",
  },
  statuses: {
    DRAFT: "Not live yet",
    READY: "Ready to go live",
    PUBLISHED: "Running",
    PAUSED: "Paused",
    ARCHIVED: "Finished",
  },
  actions: {
    publish: "Go Live",
    pause: "Pause this ad",
    resume: "Start running again",
    archive: "Turn off permanently",
    duplicate: "Make a copy",
    edit: "Make changes",
  },
  metrics: {
    impressions: "Times your ad was shown",
    reach: "Unique people who saw it",
    clicks: "People who clicked",
    ctr: "% who clicked",
    spend: "Amount spent",
    cpm: "Cost to reach 1,000 people",
    cpc: "Average cost per click",
    frequency: "Average times each person saw it",
    roas: "Revenue per £1 spent",
    purchase: "Sales from this ad",
    lead: "Contacts collected",
    videoViews: "People who watched your video",
    videoViewRate: "% who watched your video",
  },
} as const;

export const GOAL_OPTIONS = [
  { emoji: "🛒", label: "Get more sales", description: "Drive people to buy your product or service", objective: "CONVERSIONS" },
  { emoji: "🌐", label: "Get website visitors", description: "Send people to your website or online store", objective: "TRAFFIC" },
  { emoji: "📋", label: "Collect contact info", description: "Get people to fill in a form with their details", objective: "LEAD_GENERATION" },
  { emoji: "👀", label: "Get more eyes on it", description: "Show your ad to as many people as possible", objective: "REACH" },
  { emoji: "❤️", label: "Get likes and shares", description: "Make people engage with your post or page", objective: "ENGAGEMENT" },
  { emoji: "📱", label: "Get app downloads", description: "Encourage people to install your app", objective: "APP_PROMOTION" },
] as const;

export const plainObjective = (objective?: string | null) =>
  PLAIN_LANGUAGE.objectives[(objective || "") as keyof typeof PLAIN_LANGUAGE.objectives] || String(objective || "Get results").replace(/_/g, " ");

export const plainStatus = (status?: string | null) =>
  PLAIN_LANGUAGE.statuses[(status || "") as keyof typeof PLAIN_LANGUAGE.statuses] || String(status || "Not live yet").replace(/_/g, " ");
